version: '3.8'

services:
  # Relational Database Service
  postgres_db:
    image: postgres:16-alpine
    container_name: artist_postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: artist_collab_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # AI Vector Database Service
  qdrant_vector:
    image: qdrant/qdrant:v1.9.0
    container_name: artist_qdrant_container
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: